# version: "3.8"

# services:
#   api:
#     build: .
#     ports:
#       - "3000:3000" # app port
#       - "9229:9229" # debug port
#     environment:
#       DATABASE_URL: ${DATABASE_URL}
services:
  api:
    build: .
    ports:
      - "3000:3000"
      # Uncomment when debugging
      - "9229:9229"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      # Uncomment to enable debugging
      DEBUG: "true"
